version: '3.8'

services:
  app:
    image: 'application'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wilyfreddie
      - SPRING_DATASOURCE_USERNAME=wilyfreddie
      - SPRING_DATASOURCE_PASSWORD=qwerty123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=wilyfreddie
      - POSTGRES_PASSWORD=qwerty123456
      - POSTGRES_DB=wilyfreddie
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5